name: Package tests

on: 
  push:

jobs:
    my_first_job:
      runs-on: ubuntu-latest
      steps:
        - run: |
            pwd 
            ls -alF

    my_second_job:
      runs-on: ubuntu-latest
      steps:      
        - uses: actions/checkout@v3
        - run: |
            sudo apt-get update 
            sudo apt-get install tree 
            tree -F .

    my_third_job:
      runs-on: ubuntu-latest
      steps:      
        - uses: actions/checkout@v3
        - run: |
            which python
            which pip
            python --version
            pip --version
            pip install black
            black --check .

    my_fourth_job:
      runs-on: ubuntu-latest
      timeout-minutes: 5
      steps:
        - uses: actions/checkout@v3
        - run: |
            pip install coverage 
            coverage run -m pytest src/weatherfc -s
